name: Code Quality

on:
  push:
    paths:
      - "server/**"
    branches: ["master"]
  pull_request:
    paths:
      - "server/**"
    branches: ["master"]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .
